In [1]:
# Python program to demonstrate
# unary operators in numpy
import numpy as np
arr = np.array([[1, 5, 6],
[4, 7, 2],
[3, 1, 9]])
# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]


In [2]:
# minimum element of array
print ("Column-wise minimum elements:",arr.min(axis = 0))

Column-wise minimum elements: [1 1 2]


In [3]:
# sum of array elements
print ("Sum of all array elements:",arr.sum())

Sum of all array elements: 38


In [4]:
# cumulative sum along each row
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]
