In [1]:
# Python program to demonstrate
# basic operations on single array
import numpy as np
a = np.array([1, 2, 5, 3])
# add 1 to every element
print ("Adding 1 to every element:", a+1)

Adding 1 to every element: [2 3 6 4]


In [2]:
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)

Subtracting 3 from each element: [-2 -1  2  0]


In [3]:
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)

Multiplying each element by 10: [10 20 50 30]


In [4]:
# square each element
print ("Squaring each element:", a**2)

Squaring each element: [ 1  4 25  9]


In [5]:
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)

Doubled each element of original array: [ 2  4 10  6]


In [7]:
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)


Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]
