In [2]:
import numpy as np

In [3]:
# Create a 3x3 array of all zeros
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# Create a 2x2 array of all ones
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [5]:
 # Create a 3x3 constant array

c = np.full((3,3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [6]:
# Create a 3x3 array filled with random values
d = np.random.random((3,3))
print(d)

[[0.29759867 0.16460008 0.38835802]
 [0.30591627 0.08897213 0.70900652]
 [0.01258709 0.72995656 0.31809665]]


In [7]:
# Create a 3x3 identity matrix
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# convert list to array
f = np.array([2, 3, 1, 0])
print(f)

[2 3 1 0]


In [9]:
# arange() will create arrays with regularly incrementing values
g = np.arange(20)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
# note mix of tuple and lists
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [12]:
# create an array of range with float data type
i = np.arange(1, 8, dtype=float)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


In [13]:
# linspace() will create arrays with a specified number of items which are
# spaced equally between the specified beginning and end values j= np.linspace(start, stop, num)
j = np.linspace(2, 4, 5)
print(j)

[2.  2.5 3.  3.5 4. ]
