In [1]:
import numpy as np

In [2]:
# Create a rank 1 array
a = np.array([0, 1, 2])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# this will print the dimension of the array
print(a.shape)
print(a[0])
print(a[1])
print(a[2])

(3,)
0
1
2


In [4]:
# Change an element of the array
a[0] = 5
print(a)

[5 1 2]


In [5]:
# Create a rank 2 array
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3
