In [1]:
# Python program to demonstrate
# binary operators in Numpy
import numpy as np
a = np.array([[1, 2],
[3, 4]])
b = np.array([[4, 3],
[2, 1]])

In [2]:
# add arrays
print ("Array sum:\n", a + b)

Array sum:
 [[5 5]
 [5 5]]


In [3]:
# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)

Array multiplication:
 [[4 6]
 [6 4]]


In [4]:
# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Matrix multiplication:
 [[ 8  5]
 [20 13]]
